# Generated by Django 3.0.4 on 2020-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='internal_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
