# Generated by Django 3.0.4 on 2020-04-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_internal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='internal_id',
        ),
    ]
